[project]
name = "scikit-learn"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
postinstall = "pip install -e ."

[dependencies]
pip = "*"
black = ">=24.3.0"
cython = ">=3.0.10"
joblib = ">=1.2.0"
matplotlib = ">=3.3.4"
meson-python = ">=0.16.0"
mypy = ">=1.9"
numpy = ">=1.19.5"
numpydoc = ">=1.2.0"
pandas = ">=1.1.5"
plotly = ">=5.14.0"
polars = ">=0.20.30"
pooch = ">=1.6.0"
pyamg = ">=4.0.0"
pyarrow = ">=12.0.0"
pytest = ">=7.1.2"
pytest-cov = ">=2.9.0"
python = ">=3.9"
ruff = ">=0.5.1"
scikit-image = ">=0.17.2"
scipy = ">=1.6.0"
seaborn = ">=0.9.0"
threadpoolctl = ">=3.1.0"
ndonnx = ">=0.6.1,<0.7"
array-api-compat = ">=1.8,<2"
pre-commit = ">=3.8.0,<4"
